#!/usr/bin/env node
/**
 * Generates worker/src/db/seed.sql from shared/content/*.json.
 *
 * Each content file becomes one `pages` row (upserted by slug) plus one
 * `published` `revisions` row carrying its `blocks` array. Re-run any time the
 * seed content changes:
 *
 *   node worker/scripts/build-seed.mjs
 *
 * Then apply schema + seed to local D1 with:
 *
 *   npx wrangler d1 execute DB --local --file worker/src/db/schema.sql
 *   npx wrangler d1 execute DB --local --file worker/src/db/seed.sql
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const contentDir = join(__dirname, '..', '..', 'shared', 'content');
const outFile = join(__dirname, '..', 'src', 'db', 'seed.sql');

/** Escape a string for embedding in a single-quoted SQL literal. */
function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

const files = readdirSync(contentDir)
  .filter((f) => f.endsWith('.json'))
  .sort();

if (files.length === 0) {
  console.error(`No *.json files found in ${contentDir}`);
  process.exit(1);
}

let sql = '-- Generated by worker/scripts/build-seed.mjs from shared/content/*.json.\n';
sql += '-- Do not edit by hand — regenerate with: node worker/scripts/build-seed.mjs\n\n';

for (const file of files) {
  const raw = readFileSync(join(contentDir, file), 'utf8');
  /** @type {{slug: string, title: string, description: string, ground: string, blocks: unknown[]}} */
  const content = JSON.parse(raw);

  if (typeof content.slug !== 'string' || !Array.isArray(content.blocks)) {
    console.error(`Skipping ${file}: missing slug or blocks array.`);
    continue;
  }

  const meta = JSON.stringify({ description: content.description, ground: content.ground });
  const blocks = JSON.stringify(content.blocks);

  sql += `-- ${file}\n`;
  sql += `INSERT INTO pages (slug, title, meta_json) VALUES (${sqlString(content.slug)}, ${sqlString(content.title)}, ${sqlString(meta)})\n`;
  sql += `  ON CONFLICT(slug) DO UPDATE SET title = excluded.title, meta_json = excluded.meta_json;\n`;
  sql += `INSERT INTO revisions (page_id, status, blocks_json, published_at)\n`;
  sql += `  SELECT id, 'published', ${sqlString(blocks)}, datetime('now') FROM pages WHERE slug = ${sqlString(content.slug)};\n\n`;
}

writeFileSync(outFile, sql);
console.log(`Wrote ${outFile} from ${files.length} content file(s): ${files.join(', ')}`);
